version: 2.1

    jobs:
        test:
            working_directory: ~/projects/ngx-positioner
            docker:
                - image: circleci/node:10-browsers
            steps:
                - checkout
                - run:
                    name: Show current branch
                    command: echo ${CIRCLE_BRANCH}
                - restore_cache:
                    keys:
                    - v1-dependencies-{{ checksum "package-lock.json" }}
                    - v1-dependencies-
               
                - run:
                    name: Testing
                    command: npm install && npm run test --no-watch --no-progress --browsers=ChromeHeadlessCI
               
